name: Django CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      PYTHONUNBUFFERED: 1

    steps:
      # Step 1 — Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 — Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3 — Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Step 4 — Install dependencies
      - name: Install dependencies
        run: |
          pip install -r messaging_app/requirements.txt
          pip install pytest pytest-django

      # Step 5 — Wait for MySQL to be ready
      - name: Wait for MySQL
        run: |
          sudo apt-get install -y mysql-client
          until mysqladmin ping -h"$DB_HOST" --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      # Step 6 — Run Django migrations
      - name: Run migrations
        run: |
          cd messaging_app
          python manage.py migrate

      # Step 7 — Run tests with pytest
      - name: Run tests
        run: |
          cd messaging_app
          pytest --disable-warnings --maxfail=1 --junitxml=reports/results.xml

      # Step 8 — Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: messaging_app/reports/results.xml
