name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 — Set up Docker Buildx (required for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3 — Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4 — Build and push the Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./messaging_app
          file: ./messaging_app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/messaging_app:latest

      # Step 5 — Logout from Docker Hub
      - name: Log out from Docker Hub
        run: docker logout
