pipeline {
    agent any

    tools {
        python 'Python3'
    }

    environment {
        PIP_CACHE_DIR = "${WORKSPACE}/.pip-cache"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git(
                    url: 'https://github.com/sherif425/alx-backend-python.git',
                    branch: 'main',
                    credentialsId: 'github-credentials'
                )
            }
        }

        stage('Set up Python Environment') {
            steps {
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate && pip install --upgrade pip setuptools wheel'
                sh '. venv/bin/activate && pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh '. venv/bin/activate && pytest messaging_app/tests --junitxml=report.xml'
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }

        stage('Generate Coverage Report') {
            steps {
                sh '. venv/bin/activate && coverage run -m pytest messaging_app/tests'
                sh '. venv/bin/activate && coverage report'
                sh '. venv/bin/activate && coverage html'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'rm -rf venv'
        }
    }
}
